# Site settings

title: Elst Beer # Title of your site
email: info@elst.beer # Your contact email

description: > # this means to ignore newlines until "baseurl:"
  Maker of fine beer in Knoxville Tennessee.  We are inspired by the 
  tradition of Trappist Belgian breweries.  We also have a deep connection 
  with our home town of Knoxville and the beauty of the Smoky Mountains that 
  surround it.  Our goal is to create fine beers that speak to people with an 
  obsession for beer. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://elst.beer" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     elstbeer  # Replace this with your Twitter username
facebook_username:    elstbeer  # Replace this with your Facebook username

# Build settings
markdown: kramdown
